[supervisord]
nodaemon=true

[program:inspircd]
command=inspircd --foreground
autostart=true
autorestart=true

[program:thelounge]
command=thelounge start --home /config
autostart=true
autorestart=true
